<?php

class m130604_192815_languages extends CDbMigration
{
    public function safeUp()
    {
        $sql = <<< SQL
CREATE TABLE IF NOT EXISTS `languages` (
  `name` varchar(50) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `id` varchar(2) NOT NULL DEFAULT '',
  `code` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `languages` (`name`, `title`, `id`, `code`) VALUES
('Afar', 'Afaraf', 'aa', 'aar'),
('Abkhaz', 'аҧсуа бызшәа, аҧсшәа', 'ab', 'abk'),
('Avestan', 'avesta', 'ae', 'ave'),
('Afrikaans', 'Afrikaans', 'af', 'afr'),
('Akan', 'Akan', 'ak', 'aka'),
('Amharic', 'አማርኛ', 'am', 'amh'),
('Aragonese', 'aragonés', 'an', 'arg'),
('Arabic', 'العربية', 'ar', 'ara'),
('Assamese', 'অসমীয়া', 'as', 'asm'),
('Avaric', 'авар мацӀ, магӀарул мацӀ', 'av', 'ava'),
('Aymara', 'aymar aru', 'ay', 'aym'),
('Azerbaijani', 'azərbaycan dili', 'az', 'aze'),
('Bashkir', 'башҡорт теле', 'ba', 'bak'),
('Belarusian', 'беларуская мова', 'be', 'bel'),
('Bulgarian', 'български език', 'bg', 'bul'),
('Bihari', 'भोजपुरी', 'bh', 'bih'),
('Bislama', 'Bislama', 'bi', 'bis'),
('Bambara', 'bamanankan', 'bm', 'bam'),
('Bengali; Bangla', 'বাংলা', 'bn', 'ben'),
('Tibetan Standard, Tibetan, Central', 'བོད་ཡིག', 'bo', 'bod'),
('Breton', 'brezhoneg', 'br', 'bre'),
('Bosnian', 'bosanski jezik', 'bs', 'bos'),
('Catalan; Valencian', 'català, valencià', 'ca', 'cat'),
('Chechen', 'нохчийн мотт', 'ce', 'che'),
('Chamorro', 'Chamoru', 'ch', 'cha'),
('Corsican', 'corsu, lingua corsa', 'co', 'cos'),
('Cree', 'ᓀᐦᐃᔭᐍᐏᐣ', 'cr', 'cre'),
('Czech', 'čeština, český jazyk', 'cs', 'ces'),
('Old Church Slavonic, Church Slavic, Church Slavoni', 'ѩзыкъ словѣньскъ', 'cu', 'chu'),
('Chuvash', 'чӑваш чӗлхи', 'cv', 'chv'),
('Welsh', 'Cymraeg', 'cy', 'cym'),
('Danish', 'dansk', 'da', 'dan'),
('German', 'Deutsch', 'de', 'deu'),
('Divehi; Dhivehi; Maldivian;', 'ދިވެހި', 'dv', 'div'),
('Dzongkha', 'རྫོང་ཁ', 'dz', 'dzo'),
('Ewe', 'Eʋegbe', 'ee', 'ewe'),
('Greek, Modern', 'ελληνικά', 'el', 'ell'),
('English', 'English', 'en', 'eng'),
('Esperanto', 'Esperanto', 'eo', 'epo'),
('Spanish; Castilian', 'español, castellano', 'es', 'spa'),
('Estonian', 'eesti, eesti keel', 'et', 'est'),
('Basque', 'euskara, euskera', 'eu', 'eus'),
('Persian', 'فارسی', 'fa', 'fas'),
('Fula; Fulah; Pulaar; Pular', 'Fulfulde, Pulaar, Pular', 'ff', 'ful'),
('Finnish', 'suomi, suomen kieli', 'fi', 'fin'),
('Fijian', 'vosa Vakaviti', 'fj', 'fij'),
('Faroese', 'føroyskt', 'fo', 'fao'),
('French', 'français, langue française', 'fr', 'fra'),
('Western Frisian', 'Frysk', 'fy', 'fry'),
('Irish', 'Gaeilge', 'ga', 'gle'),
('Scottish Gaelic; Gaelic', 'Gàidhlig', 'gd', 'gla'),
('Galician', 'galego', 'gl', 'glg'),
('Guaraní', 'Avañe''ẽ', 'gn', 'grn'),
('Gujarati', 'ગુજરાતી', 'gu', 'guj'),
('Manx', 'Gaelg, Gailck', 'gv', 'glv'),
('Hausa', 'Hausa, هَوُسَ', 'ha', 'hau'),
('Hebrew (modern)', 'עברית', 'he', 'heb'),
('Hindi', 'हिन्दी, हिंदी', 'hi', 'hin'),
('Hiri Motu', 'Hiri Motu', 'ho', 'hmo'),
('Croatian', 'hrvatski jezik', 'hr', 'hrv'),
('Haitian; Haitian Creole', 'Kreyòl ayisyen', 'ht', 'hat'),
('Hungarian', 'magyar', 'hu', 'hun'),
('Armenian', 'Հայերեն', 'hy', 'hye'),
('Herero', 'Otjiherero', 'hz', 'her'),
('Interlingua', 'Interlingua', 'ia', 'ina'),
('Indonesian', 'Bahasa Indonesia', 'id', 'ind'),
('Interlingue', 'Originally called Occidental; then Interlingue aft', 'ie', 'ile'),
('Igbo', 'Asụsụ Igbo', 'ig', 'ibo'),
('Nuosu', 'ꆈꌠ꒿ Nuosuhxop', 'ii', 'iii'),
('Inupiaq', 'Iñupiaq, Iñupiatun', 'ik', 'ipk'),
('Ido', 'Ido', 'io', 'ido'),
('Icelandic', 'Íslenska', 'is', 'isl'),
('Italian', 'italiano', 'it', 'ita'),
('Inuktitut', 'ᐃᓄᒃᑎᑐᑦ', 'iu', 'iku'),
('Japanese', '日本語 (にほんご)', 'ja', 'jpn'),
('Javanese', 'basa Jawa', 'jv', 'jav'),
('Georgian', 'ქართული', 'ka', 'kat'),
('Kongo', 'KiKongo', 'kg', 'kon'),
('Kikuyu, Gikuyu', 'Gĩkũyũ', 'ki', 'kik'),
('Kwanyama, Kuanyama', 'Kuanyama', 'kj', 'kua'),
('Kazakh', 'қазақ тілі', 'kk', 'kaz'),
('Kalaallisut, Greenlandic', 'kalaallisut, kalaallit oqaasii', 'kl', 'kal'),
('Khmer', 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ', 'km', 'khm'),
('Kannada', 'ಕನ್ನಡ', 'kn', 'kan'),
('Korean', '한국어 (韓國語), 조선어 (朝鮮語)', 'ko', 'kor'),
('Kanuri', 'Kanuri', 'kr', 'kau'),
('Kashmiri', 'कश्मीरी, كشميري‎', 'ks', 'kas'),
('Kurdish', 'Kurdî, كوردی‎', 'ku', 'kur'),
('Komi', 'коми кыв', 'kv', 'kom'),
('Cornish', 'Kernewek', 'kw', 'cor'),
('Kyrgyz', 'Кыргызча, Кыргыз тили', 'ky', 'kir'),
('Latin', 'latine, lingua latina', 'la', 'lat'),
('Luxembourgish, Letzeburgesch', 'Lëtzebuergesch', 'lb', 'ltz'),
('Ganda', 'Luganda', 'lg', 'lug'),
('Limburgish, Limburgan, Limburger', 'Limburgs', 'li', 'lim'),
('Lingala', 'Lingála', 'ln', 'lin'),
('Lao', 'ພາສາລາວ', 'lo', 'lao'),
('Lithuanian', 'lietuvių kalba', 'lt', 'lit'),
('Luba-Katanga', 'Tshiluba', 'lu', 'lub'),
('Latvian', 'latviešu valoda', 'lv', 'lav'),
('Malagasy', 'fiteny malagasy', 'mg', 'mlg'),
('Marshallese', 'Kajin M̧ajeļ', 'mh', 'mah'),
('Māori', 'te reo Māori', 'mi', 'mri'),
('Macedonian', 'македонски јазик', 'mk', 'mkd'),
('Malayalam', 'മലയാളം', 'ml', 'mal'),
('Mongolian', 'монгол', 'mn', 'mon'),
('Marathi (Marāṭhī)', 'मराठी', 'mr', 'mar'),
('Malay', 'bahasa Melayu, بهاس ملايو‎', 'ms', 'msa'),
('Maltese', 'Malti', 'mt', 'mlt'),
('Burmese', 'ဗမာစာ', 'my', 'mya'),
('Nauru', 'Ekakairũ Naoero', 'na', 'nau'),
('Norwegian Bokmål', 'Norsk bokmål', 'nb', 'nob'),
('North Ndebele', 'isiNdebele', 'nd', 'nde'),
('Nepali', 'नेपाली', 'ne', 'nep'),
('Ndonga', 'Owambo', 'ng', 'ndo'),
('Dutch', 'Nederlands, Vlaams', 'nl', 'nld'),
('Norwegian Nynorsk', 'Norsk nynorsk', 'nn', 'nno'),
('Norwegian', 'Norsk', 'no', 'nor'),
('South Ndebele', 'isiNdebele', 'nr', 'nbl'),
('Navajo, Navaho', 'Diné bizaad, Dinékʼehǰí', 'nv', 'nav'),
('Chichewa; Chewa; Nyanja', 'chiCheŵa, chinyanja', 'ny', 'nya'),
('Occitan', 'occitan, lenga d''òc', 'oc', 'oci'),
('Ojibwe, Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'oj', 'oji'),
('Oromo', 'Afaan Oromoo', 'om', 'orm'),
('Oriya', 'ଓଡ଼ିଆ', 'or', 'ori'),
('Ossetian, Ossetic', 'ирон æвзаг', 'os', 'oss'),
('Panjabi, Punjabi', 'ਪੰਜਾਬੀ, پنجابی‎', 'pa', 'pan'),
('Pāli', 'पाऴि', 'pi', 'pli'),
('Polish', 'język polski, polszczyzna', 'pl', 'pol'),
('Pashto, Pushto', 'پښتو', 'ps', 'pus'),
('Portuguese', 'português', 'pt', 'por'),
('Quechua', 'Runa Simi, Kichwa', 'qu', 'que'),
('Romansh', 'rumantsch grischun', 'rm', 'roh'),
('Kirundi', 'Ikirundi', 'rn', 'run'),
('Romanian, Moldavian(Romanian from Republic of Mold', 'limba română', 'ro', 'ron'),
('Russian', 'русский язык', 'ru', 'rus'),
('Kinyarwanda', 'Ikinyarwanda', 'rw', 'kin'),
('Sanskrit (Saṁskṛta)', 'संस्कृतम्', 'sa', 'san'),
('Sardinian', 'sardu', 'sc', 'srd'),
('Sindhi', 'सिन्धी, سنڌي، سندھی‎', 'sd', 'snd'),
('Northern Sami', 'Davvisámegiella', 'se', 'sme'),
('Sango', 'yângâ tî sängö', 'sg', 'sag'),
('Sinhala, Sinhalese', 'සිංහල', 'si', 'sin'),
('Slovak', 'slovenčina, slovenský jazyk', 'sk', 'slk'),
('Slovene', 'slovenski jezik, slovenščina', 'sl', 'slv'),
('Samoan', 'gagana fa''a Samoa', 'sm', 'smo'),
('Shona', 'chiShona', 'sn', 'sna'),
('Somali', 'Soomaaliga, af Soomaali', 'so', 'som'),
('Albanian', 'gjuha shqipe', 'sq', 'sqi'),
('Serbian', 'српски језик', 'sr', 'srp'),
('Swati', 'SiSwati', 'ss', 'ssw'),
('Southern Sotho', 'Sesotho', 'st', 'sot'),
('Sundanese', 'Basa Sunda', 'su', 'sun'),
('Swedish', 'Svenska', 'sv', 'swe'),
('Swahili', 'Kiswahili', 'sw', 'swa'),
('Tamil', 'தமிழ்', 'ta', 'tam'),
('Telugu', 'తెలుగు', 'te', 'tel'),
('Tajik', 'тоҷикӣ, toğikī, تاجیکی‎', 'tg', 'tgk'),
('Thai', 'ไทย', 'th', 'tha'),
('Tigrinya', 'ትግርኛ', 'ti', 'tir'),
('Turkmen', 'Türkmen, Түркмен', 'tk', 'tuk'),
('Tagalog', 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔', 'tl', 'tgl'),
('Tswana', 'Setswana', 'tn', 'tsn'),
('Tonga (Tonga Islands)', 'faka Tonga', 'to', 'ton'),
('Turkish', 'Türkçe', 'tr', 'tur'),
('Tsonga', 'Xitsonga', 'ts', 'tso'),
('Tatar', 'татар теле, tatar tele', 'tt', 'tat'),
('Twi', 'Twi', 'tw', 'twi'),
('Tahitian', 'Reo Tahiti', 'ty', 'tah'),
('Uighur, Uyghur', 'Uyƣurqə, ئۇيغۇرچە‎', 'ug', 'uig'),
('Ukrainian', 'українська мова', 'uk', 'ukr'),
('Urdu', 'اردو', 'ur', 'urd'),
('Uzbek', 'O''zbek, Ўзбек, أۇزبېك‎', 'uz', 'uzb'),
('Venda', 'Tshivenḓa', 've', 'ven'),
('Vietnamese', 'Tiếng Việt', 'vi', 'vie'),
('Volapük', 'Volapük', 'vo', 'vol'),
('Walloon', 'walon', 'wa', 'wln'),
('Wolof', 'Wollof', 'wo', 'wol'),
('Xhosa', 'isiXhosa', 'xh', 'xho'),
('Yiddish', 'ייִדיש', 'yi', 'yid'),
('Yoruba', 'Yorùbá', 'yo', 'yor'),
('Zhuang, Chuang', 'Saɯ cueŋƅ, Saw cuengh', 'za', 'zha'),
('Chinese', '中文 (Zhōngwén), 汉语, 漢語', 'zh', 'zho'),
('Zulu', 'isiZulu', 'zu', 'zul');
SQL;

        $this->execute($sql);
    }

    public function safeDown()
    {

    }
}